#Requires -Version 5.1
<#
.SYNOPSIS
  Write a hunt checklist for one map bbox (SRTM + OSM) under Research/maps/raw/<Id>/.
.PARAMETER Id
  Fixture id (folder name), e.g. lrt-1863
#>
param(
    [Parameter(Mandatory = $true)][string]$Id,
    [Parameter(Mandatory = $true)][double]$West,
    [Parameter(Mandatory = $true)][double]$South,
    [Parameter(Mandatory = $true)][double]$East,
    [Parameter(Mandatory = $true)][double]$North,
    [int]$Width = 128,
    [int]$Height = 128,
    [double]$MetresPerCell = 25
)

$ErrorActionPreference = "Stop"
$repoRoot = Resolve-Path (Join-Path $PSScriptRoot "..\..")
$outDir = Join-Path $repoRoot "Research\maps\raw\$Id"
New-Item -ItemType Directory -Force -Path $outDir | Out-Null

if ($East -le $West -or $North -le $South) {
    throw "BBox invalid: need East>West and North>South."
}

$midLon = ($West + $East) / 2.0
$midLat = ($South + $North) / 2.0
$zone = [int][math]::Floor(($midLon + 180.0) / 6.0) + 1
$band = if ($midLat -ge 0) { "N" } else { "M" }  # rough; operator confirms MGRS band

$sheetW = $Width * $MetresPerCell
$sheetH = $Height * $MetresPerCell

$overpass = @"
[out:xml][timeout:90];
(
  way["highway"]($South,$West,$North,$East);
  node["place"~"city|town|village|hamlet"]($South,$West,$North,$East);
);
out body;
>;
out skel qt;
"@

$hunt = @"
# Hunt — $Id

Generated by ``tools/maps/hunt-bbox.ps1`` for Strategos map import (#493).

## BBox (WGS84)

| | |
|---|---|
| West / South | $West / $South |
| East / North | $East / $North |
| Centre | $midLon, $midLat |
| Suggested UTM zone | $zone (confirm band; placeholder band letter: $band) |
| Target grid | ${Width} x ${Height} @ ${MetresPerCell} m/cell (~${sheetW} m x ${sheetH} m) |

## 1. DEM (SRTM)

- OpenTopography: https://portal.opentopography.org/datasets
- USGS EarthExplorer: https://earthexplorer.usgs.gov (SRTM 1 Arc-Second)
- terrain.party (quick bbox): https://terrain.party

Save the cropped GeoTIFF or HGT as:

``Research/maps/raw/$Id/dem.tif``

Licence: Public Domain (US Government / SRTM). Record exact dataset name in PROVENANCE.

## 2. OSM (roads / settlements)

Paste into https://overpass-turbo.eu → Export → download OSM XML:

``````
$overpass
``````

Or Geofabrik extract + clip. Save as:

``Research/maps/raw/$Id/export.osm``

Licence: ODbL — credit required in-game (see ATTRIBUTIONS.md).

## 3. Convert

From repo root (requires GDAL on PATH):

``````powershell
./tools/maps/convert-dem.ps1 -Id $Id -Input Research/maps/raw/$Id/dem.tif ``
  -Width $Width -Height $Height -MetresPerCell $MetresPerCell ``
  -Zone $zone -Band $band -Easting <SW_EASTING> -Northing <SW_NORTHING>

./tools/maps/convert-osm.ps1 -Id $Id -Input Research/maps/raw/$Id/export.osm ``
  -Width $Width -Height $Height -MetresPerCell $MetresPerCell ``
  -Zone $zone -Band $band -Easting <SW_EASTING> -Northing <SW_NORTHING>

./tools/maps/validate-fixture.ps1 -Id $Id
``````

Pick ``Easting`` / ``Northing`` as the UTM position of the **south-west** corner of
cell (0,0) — same as ``GeoOrigin`` in MapData. Use ``gdalinfo`` / QGIS or an online
WGS84→UTM converter on ($West, $South).

## Docs

- docs/map-import-tools.md
- docs/assets.md
"@

$huntPath = Join-Path $outDir "HUNT.md"
Set-Content -Path $huntPath -Value $hunt -Encoding utf8
Write-Host "Wrote $huntPath"
Write-Host "Next: download dem.tif / export.osm into $outDir"
